### PR TITLE
Added powershell script for Windows

### PR DESCRIPTION
**Pull request by sbueringer**
So that's the powershell script I mentioned [here](https://github.com/app-registry/appr/issues/56). I'm not sure how the command in the plugin.yaml has to be so that it uses cnr.sh or cnr.ps1 depending on the OS.

The powershell script was also requested here #14

### CODE REVIEW

**Comment by jzelinskie** [comment]
I talked to upstream and there isn't anyway to pivot on which script depending on OS.
I did see on stackoverflow there's some nasty hacks to embed bash/cmd into one script using some hacks...

I'm not quite sure the best way to move forward here.

**Comment by ant31** [comment]
@jzelinskie we can  release two zip file, containing different plugin.yaml, 1 for linux* 1 for windows.

**Comment by ant31** [comment]
@jzelinskie @sbueringer , latest appr release will allow to directly use the cli without a shell-script. 
on the `plugin.yaml` command will be `appr helm` . 

And because there is no more shell/ps script required, we should probably merge both repo too: 
appr and appr-helm-plugin.


https://github.com/app-registry/appr/pull/71

**Comment by sbueringer** [comment]
@ant31 Sounds good and it's obivously the better solution.

**Pull request merged**
